"""empty message

Revision ID: 025f504bc0ee
Revises: 87596a984a70
Create Date: 2024-02-22 16:58:21.640820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025f504bc0ee'
down_revision = '87596a984a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
