"""empty message

Revision ID: 9d101db312b2
Revises: cdd22672b6ad
Create Date: 2024-05-01 17:30:15.541694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d101db312b2'
down_revision = 'cdd22672b6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_story_id', 'story', ['story_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_story_id', type_='foreignkey')
        batch_op.drop_column('story_id')

    # ### end Alembic commands ###
