"""empty message

Revision ID: f9e61e35a78e
Revises: 9d101db312b2
Create Date: 2024-06-19 15:56:48.284959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e61e35a78e'
down_revision = '9d101db312b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags_string', sa.String(length=255), nullable=True))
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('tags_string')

    # ### end Alembic commands ###
